# Generated by Django 3.0.6 on 2020-12-23 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=31, null=True)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Encomendado'), (1, 'Separado'), (2, 'Saiu para Entrega'), (3, 'Entregue')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('buy_value', models.FloatField()),
                ('sell_value', models.FloatField()),
                ('stock', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_value', models.FloatField()),
                ('liquid_value', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=31)),
                ('description', models.CharField(blank=True, max_length=127, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('value', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backoffice.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=127, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=127, null=True)),
                ('state', models.CharField(blank=True, max_length=63, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=31, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Client')),
            ],
        ),
    ]
