# Generated by Django 3.0.6 on 2021-01-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20210102_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spendings',
            new_name='Spending',
        ),
    ]
