# Generated by Django 3.1.5 on 2021-02-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20210103_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproductlist',
            old_name='order',
            new_name='purchase',
        ),
    ]
